[[pages]]
path = "profile_picture.py"
name = "Instagram Profile Picture"
icon = "ğŸ‘¤"

[[pages]]
path = "thumbnail_reels.py"
name = "Thumbnail Reels"
icon = "ğŸ“·"

[[pages]]
path = "thumbnail_tiktok.py"
name = "Thumbnail TikTok"
icon = "ğŸ¬"
